FROM quay.io/keycloak/keycloak:latest

COPY --chown=keycloak:root bank-realm.json /opt/keycloak/data/import/bank-realm.json
# COPY --chown=keycloak:root fida-realm.json /opt/keycloak/data/import/fida-realm.json